---
title: "5_31_TidyTuesday"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
library("gridExtra")
```

```{r}
poll <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/poll.csv')
reputation <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-31/reputation.csv')
```



```{r}
top_2022 <- poll %>%
   rename(rank_2022 = `2022_rank`) %>%
  filter(rank_2022 < 21)
```






```{r}
industry_2021 <- poll %>%
  rename(rank_2022 = `2022_rank`) %>%
  drop_na(rank) %>%
  filter(year == 2021) %>%
  group_by(industry) %>%
  count()
```

```{r}
industry_2021 <- industry_2021 %>%
  mutate(proportion = n/100)
```

```{r}
a <- industry_2021 %>%
  ggplot(aes(x="", y=proportion, fill = industry, label = proportion)) +
  guides(fill=guide_legend(override.aes=list(colour=NA))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
   theme_void()+
   ggtitle("2021 Rankings By Industry")

a <- plot_ly(industry_2021, labels = ~industry, values = ~proportion, type = 'pie',textposition = 'outside',textinfo = 'label+percent') %>%
  layout(title = '2021 Number of Top 100 per Industry',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

a

  
```

```{r}
industry_2020 <- poll %>%
  rename(rank_2022 = `2022_rank`) %>%
  drop_na(rank) %>%
  filter(year == 2020) %>%
  group_by(industry) %>%
  count() %>%
  mutate(proportion = n/100)
```

```{r}
b <- industry_2020 %>%
  ggplot(aes(x="", y=proportion, fill = industry, label = proportion)) +
  guides(fill=guide_legend(override.aes=list(colour=NA))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
   theme_void()+
   ggtitle("2020 Rankings By Industry")

b <- plot_ly(industry_2020, labels = ~industry, values = ~proportion, type = 'pie',textposition = 'outside',textinfo = 'label+percent') %>%
  layout(title = '2020 Number of Top 100 per Industry',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

b

```

```{r}
industry_2019 <- poll %>%
  rename(rank_2022 = `2022_rank`) %>%
  drop_na(rank) %>%
  filter(year == 2019) %>%
  group_by(industry) %>%
  count() %>%
  mutate(proportion = n/100)
```

```{r}
c <- industry_2019 %>%
  ggplot(aes(x="", y=proportion, fill = industry, label = proportion)) +
  guides(fill=guide_legend(override.aes=list(colour=NA))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
   theme_void()+
   ggtitle("2019 Rankings By Industry")

c <-  plot_ly(industry_2019, labels = ~industry, values = ~proportion, type = 'pie',textposition = 'outside',textinfo = 'label+percent') %>%
  layout(title = '2019 Number of Top 100 per Industry',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

c

```

```{r}
industry_2018 <- poll %>%
  rename(rank_2022 = `2022_rank`) %>%
  drop_na(rank) %>%
  filter(year == 2018) %>%
  group_by(industry) %>%
  count() %>%
  mutate(proportion = n/100)
```

```{r}
d <- industry_2018 %>%
  ggplot(aes(x="", y=proportion, fill = industry, label = proportion)) +
  guides(fill=guide_legend(override.aes=list(colour=NA))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
   theme_void()+
   ggtitle("2018 Rankings By Industry")

d <- plot_ly(industry_2018, labels = ~industry, values = ~proportion, type = 'pie',textposition = 'outside',textinfo = 'label+percent') %>%
  layout(title = '2018 Number of Top 100 per Industry',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

d
```

```{r}
industry_2017 <- poll %>%
  rename(rank_2022 = `2022_rank`) %>%
  drop_na(rank) %>%
  filter(year == 2017) %>%
  group_by(industry) %>%
  count() %>%
  mutate(proportion = n/100)

  y.breaks.2017 <- cumsum(industry_2017$proportion) - industry_2017$proportion/2
```

```{r}
library(plotly)

e <- plot_ly(industry_2017, labels = ~industry, values = ~proportion, type = 'pie',textposition = 'outside',textinfo = 'label+percent') %>%
  layout(title = '2018 Number of Top 100 per Industry',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

e
```


```{r}
e <- industry_2017 %>%
  ggplot(aes(x="", y=proportion, fill = industry)) +
  guides(fill=guide_legend(override.aes=list(colour=NA))) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+
   ggtitle("2017 Rankings By Industry") + scale_y_continuous(
        breaks=y.breaks.2017,   # where to place the labels
        labels=industry_2017$industry)
e
```

```{r}
fig <- plot_ly() 

fig <- fig %>% add_pie(data = industry_2017, labels = ~industry, values = ~proportion,
                         name = "2017", domain = list(row = 0, column = 0))
fig <- fig %>% add_pie(data = industry_2018, labels = ~industry, values = ~proportion,
                         name = "2018", domain = list(row = 0, column = 1))
fig <- fig %>% add_pie(data = industry_2019, labels = ~industry, values = ~proportion,
                         name = "2019", domain = list(row = 1, column = 0))
fig <- fig %>% add_pie(data = industry_2020, labels = ~industry, values = ~proportion,
                         name = "2020", domain = list(row = 1, column = 1))
fig <- fig %>% add_pie(data = industry_2021, labels = ~industry, values = ~proportion,
                         name = "2021", domain = list(row = 2, column = 2))

fig <- fig %>% layout(title = "Proportion of Top 100 Rankings per Industry by Year", showlegend = F,
                      grid=list(rows=3, columns=2),
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig
```

