---
title: "7-19-2022 Tidy_Tuesday"
output: html_document
date: '2022-07-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(countrycode)
library(geofacet)
library(lubridate)
library(NatParksPalettes)
library(paRkpal)
```


```{r message=FALSE}
technology <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-19/technology.csv')
anti_LGBTQ_countries <- read_csv('antiLGBTQ_data.csv')
violence <- read_csv("GEDEvent_v22_1 2.csv")
```

```{r}
anti_LGBTQ_list <- anti_LGBTQ_countries$Countries
```

```{r}
strat_sample_1 <- strat_sample %>%
  rename(country = country_name)

violence %>%
  filter(country %in% strat_sample_1)
```

```{r}
max_violence <- violence %>%
  group_by(country) %>%
  filter(deaths_civilians == max(deaths_civilians)) %>%
  select(country, everything())

max_violence_new <- max_violence %>% 
  filter(country %in% strat_sample$country_name) %>%
  rename(country_name = country)%>%
  mutate(year = year(date_start)) %>%
  select(country_name, year, active_year, deaths_civilians) %>%
  mutate(end_year = year + active_year)
```




```{r}
technology %>%
  select(category) %>%
  unique()
```

```{r}
technology_country %>%
  group_by(continent) %>%
  count()
```

```{r}
technology_country %>%
  filter(is.na(continent))
```


```{r}
technology %>%
  filter(category == "Vaccines")
```

```{r}
technology_country <- technology %>%
  mutate(country_name = countrycode(iso3c, origin = 'iso3c', destination = 'country.name')) %>%
  mutate(country_name = case_when(
    iso3c == "ANT" ~ "Netherlands Antilles",
    iso3c == "CSK" ~ "Czechoslovakia",
    iso3c == "ROM" ~ "Romania",
    iso3c == "XKX" ~ "Kosovo",
    iso3c == "XCD" ~ "Carribean", #not totally sure on this one
    TRUE ~ country_name)) %>%
  mutate(continent = countrycode(country_name, origin = 'country.name', destination = 'continent')) %>%
  mutate(continent = case_when(
    country_name == "Kosovo" ~ "Europe",
    country_name == "Antarctica" ~ "Antarctica",
    country_name == "Czechoslovakia" ~ "Europe",
    country_name == "Carribean" ~ "Americas",
    TRUE ~ continent))
```
```{r}
set.seed(47)

strat_sample <- technology_country %>%
  select(continent, country_name) %>%
  filter(country_name != "Antarctica") %>%
  group_by(continent) %>%
  sample_n(size = 10) 

strat_sample_1 <- strat_sample %>%
  filter(country_name != "Niue")
```




```{r}
technology_country %>%
  select(group,category) %>%
  group_by(group,category) %>%
  unique()
```

```{r}
max_violence_year <- max_violence_new %>%
  select(country_name, year, end_year)
```


```{r}
technology_country %>%
  filter(category == "Vaccines") %>%
  filter(country_name %in% max_violence_new$country_name) %>%
  filter(label == "% children who received a IPV1 immunization") %>%
  ggplot(aes(x = year, y = value))+
  xlim(c(1990,2020))+
  geom_point(size = 2)+
  geom_vline(data = max_violence_year, aes(xintercept =  year), color = "blue")+
  geom_vline(data = max_violence_year, aes(xintercept =  end_year), color = "blue")+
    facet_wrap(~country_name)
```

```{r}
technology_country %>%
  filter(category == "Vaccines") %>%
  filter(country_name %in% max_violence_new$country) %>%
  drop_na(value) %>%
  group_by(label) %>%
  summarize(mean_val = mean(value)) %>%
  arrange(desc(mean_val))
```


```{r}
Vaccine <- technology_country %>%
  filter(category == "Vaccines")
```


```{r}
tech_depression <- technology_country %>%
  filter(category == "Vaccines") %>%
  filter(label == "N06A-Antidepressants (defined daily dosage)") %>%
  filter(country_name != "New Zealand")                                                                                                              

tech_nervous <- technology_country %>%
  filter(category == "Vaccines") %>%
  filter(label == "N-Nervous system (defined daily dosage)") %>%
  filter(country_name != "New Zealand")
```


```{r}
tech_energy$label %>%
  unique()
```
```{r}
tech_energy_avg <- technology_country %>%
  filter(category == "Energy") %>%
  filter(label == "Electric power consumption (KWH)") %>%
  group_by(country_name) %>%
  summarize(mean_val = mean(value)) %>%
  arrange(desc(mean_val)) 

top_tech_energy_avg <- tech_energy_avg %>%
  slice_head(n = 20)
```

```{r}
tech_energy <- technology_country %>%
  filter(category == "Energy") %>%
  filter(grepl("from",label)) %>%
  mutate_at("label", str_replace, "(?=\\().*?(?<=\\))", "") %>%
  filter(country_name %in% top_tech_energy_avg$country_name)

tech_energy$label <- factor(tech_energy$label, levels = c("Electricity from coal ", "Electricity from oil ", "Electricity from gas ", "Electricity from nuclear ", "Electricity from hydro ", "Electricity from wind ", "Electricity from solar ", "Electricity from other renewables "))
```


```{r}
tech_plot_1 <- tech_energy %>%
  ggplot(aes(x = year, y = value))+
  xlim(c(1980,2020))+
  geom_point(size = .5, aes(color = label))+
  geom_line(aes(color = label))+
    facet_wrap(~country_name, scales = "free_y")+
  scale_color_manual(values = park_palette("smoky_mountains2", n = 8))+
  theme_bw()+
  theme(legend.position = "top", legend.justification = "left", legend.title = element_text(face = "bold"), title = element_text(size = 15), legend.text = element_text(color = "black",size = 11), axis.title = element_text(face = "bold"), legend.background = element_rect(fill = "gray95"), axis.text = element_text(color = "black"), strip.text = element_text(color = "black", face = "bold"))+
  guides(color = guide_legend(title.position = "top", title = "Energy Usage in Terrawatt Hours (TWh)"))+
  ylab("Annual Number of TWh")+
  xlab("Year (1980-2020)")+
  ggtitle("Comparing Types of Energy Usage by Country")+
  theme(plot.title = element_text(size = 17, face = "bold", hjust = 0.5))+
  labs(caption ="Tidy Tuesday 07-19-2022 | GitHub: @scolando")+
  theme(plot.background = element_rect(fill = "gray95"))

tech_plot_1
```

```{r}
ggsave("tech_plot_1.png", tech_plot_1, width = 15, height = 7)
```


```{r}
tech_plot_2 <- tech_energy %>%
  ggplot(aes(x = year, y = value))+
  xlim(c(1980,2020))+
  geom_point(size = .5, aes(color = label))+
  geom_line(aes(color = label))+
    facet_wrap(~country_name)+
  scale_color_manual(values = park_palette("smoky_mountains2", n = 8))+
  theme_bw()+
  theme(legend.position = "top", legend.justification = "left", legend.title = element_text(face = "bold"), title = element_text(size = 15), legend.text = element_text(color = "black",size = 11), axis.title = element_text(face = "bold"), legend.background = element_rect(fill = "gray95"), axis.text = element_text(color = "black"), strip.text = element_text(color = "black", face = "bold"))+
  guides(color = guide_legend(title.position = "top", title = "Energy Usage in Terrawatt Hours (TWh)"))+
  ylab("Annual Number of TWh")+
  xlab("Year (1980-2020)")+
  ggtitle("Comparing Types of Energy Usage by Country")+
  theme(plot.title = element_text(size = 14, face = "bold", hjust = 0.5))+
  labs(caption ="Tidy Tuesday 07-19-2022 | GitHub: @scolando")+
  theme(plot.background = element_rect(fill = "gray95"))

tech_plot_2
```
```{r}
ggsave("tech_plot_2.png", tech_plot_2, width = 15, height = 7)
```

